# Generated by Django 3.0 on 2021-11-12 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20211112_1442'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='category',
            new_name='cate',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='position',
            new_name='pos',
        ),
    ]
