# Generated by Django 3.0 on 2021-11-12 07:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0009_auto_20211112_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='cate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Category'),
        ),
        migrations.AlterField(
            model_name='post',
            name='money',
            field=models.CharField(choices=[(1, 'have'), (2, 'dont have')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='pos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Position'),
        ),
    ]
