# Generated by Django 3.0 on 2021-11-12 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_auto_20211112_1445'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='category',
        ),
        migrations.RemoveField(
            model_name='position',
            name='position',
        ),
        migrations.RemoveField(
            model_name='post',
            name='cate',
        ),
        migrations.RemoveField(
            model_name='post',
            name='pos',
        ),
        migrations.AddField(
            model_name='category',
            name='cat_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='position',
            name='pos_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
