# Generated by Django 3.0 on 2021-11-12 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_auto_20211112_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cate',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myapp.Category'),
        ),
    ]
