# Generated by Django 3.0 on 2021-11-16 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_bookmark'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookmark',
            old_name='postmark',
            new_name='bookmark',
        ),
        migrations.RenameField(
            model_name='bookmark',
            old_name='postmarkid',
            new_name='bookmarkId',
        ),
    ]
