# Generated by Django 3.0 on 2021-11-17 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_auto_20211117_0224'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='Intern_type',
            field=models.CharField(choices=[('ฝึกงาน', 'ฝึกงาน'), ('ทำงาน', 'ทำงาน')], max_length=255, null=True),
        ),
    ]
