# Generated by Django 3.0 on 2021-11-21 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_auto_20211120_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Intern_type',
            field=models.CharField(choices=[('ฝึกงาน', 'ฝึกงาน'), ('งานประจำ', 'งานประจำ'), ('ฟรีแลนซ์', 'ฟรีแลนซ์'), ('พาร์ทไทม์', 'พาร์ทไทม์'), ('สัญญาจ้าง', 'สัญญาจ้าง')], max_length=255),
        ),
        migrations.AlterField(
            model_name='post',
            name='rating',
            field=models.CharField(choices=[('น้อยมาก', 'น้อยมาก'), ('น้อย', 'น้อย'), ('พอใช้', 'พอใช้'), ('มาก', 'มาก'), ('มากที่สุด', 'มากที่สุด')], max_length=255),
        ),
    ]
