# Generated by Django 3.0 on 2021-11-21 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_auto_20211121_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='province',
            name='prov_name',
            field=models.CharField(max_length=255),
        ),
    ]
