# Generated by Django 3.0 on 2021-11-21 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_auto_20211121_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='prov',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.Province'),
        ),
    ]
