# Generated by Django 3.0 on 2021-11-21 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_auto_20211121_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='prov',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Province'),
        ),
    ]
