# Generated by Django 3.0 on 2021-11-21 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_auto_20211121_2023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='location2',
        ),
        migrations.RemoveField(
            model_name='post',
            name='location3',
        ),
        migrations.RemoveField(
            model_name='post',
            name='location4',
        ),
    ]
