# Generated by Django 3.0 on 2021-11-21 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0027_auto_20211121_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='prov',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.Province'),
        ),
        migrations.AlterField(
            model_name='province',
            name='prov_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
