# Generated by Django 3.0 on 2021-11-21 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0028_auto_20211121_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='location2',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='location3',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='location4',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
