# Generated by Django 3.0 on 2021-11-23 09:24

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0030_profile_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=ckeditor.fields.RichTextField(blank=True, default='Hi! Im new user', max_length=500, null=True),
        ),
    ]
