# Generated by Django 3.0 on 2022-03-29 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0039_otherpostimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='image',
            new_name='thumbnail',
        ),
        migrations.AlterField(
            model_name='otherpostimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='otherPostImage/'),
        ),
    ]
