# Generated by Django 3.0 on 2022-04-05 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0040_auto_20220329_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='tel',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
