# Generated by Django 3.0 on 2022-04-15 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0041_profile_tel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Intern_type',
            field=models.CharField(choices=[('ปกติ', 'ปกติ'), ('สหกิจ', 'สหกิจ')], max_length=255),
        ),
        migrations.AlterField(
            model_name='post',
            name='rating',
            field=models.CharField(choices=[('น้อยมาก', 'น้อยมาก'), ('น้อย', 'น้อย'), ('พอใช้', 'พอใช้'), ('มาก', 'มาก'), ('มากที่สุด', 'มากที่สุด')], max_length=255),
        ),
    ]
