# Generated by Django 3.0 on 2022-04-15 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0042_auto_20220415_0737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='rating',
            field=models.CharField(choices=[('น้อยมาก', 'น้อยมาก'), ('น้อย', 'น้อย'), ('ปานกลาง', 'ปานกลาง'), ('มาก', 'มาก'), ('มากที่สุด', 'มากที่สุด')], max_length=255),
        ),
    ]
