# Generated by Django 3.0 on 2022-04-17 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0043_auto_20220415_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='money_type',
            field=models.CharField(choices=[('วัน', 'วัน'), ('สัปดาห์', 'สัปดาห์'), ('เดือน', 'เดือน')], max_length=255, null=True),
        ),
    ]
