# Generated by Django 3.0 on 2022-04-30 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0046_auto_20220429_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
