# Generated by Django 3.0 on 2022-05-03 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0047_auto_20220501_0500'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='introduce',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
