# Generated by Django 3.0 on 2022-05-08 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0053_auto_20220509_0515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='money',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
    ]
