# Generated by Django 3.0 on 2022-05-09 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0056_auto_20220509_1410'),
    ]

    operations = [
        migrations.CreateModel(
            name='internWorks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work', models.CharField(blank=True, max_length=500, null=True)),
                ('work_name', models.CharField(blank=True, max_length=500, null=True)),
                ('work_detail', models.CharField(blank=True, max_length=1000)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Post')),
            ],
        ),
    ]
