# Generated by Django 3.0 on 2022-05-12 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0057_internworks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Intern_type',
            field=models.CharField(choices=[('1-2 เดือน', '1-2 เดือน'), ('2-3 เดือน', '2-3 เดือน'), ('3-4 เดือน', '3-4 เดือน'), ('4-5 เดือน', '4-5 เดือน'), ('6 เดือนขึ้นไป', '6 เดือนขึ้นไป')], max_length=255),
        ),
    ]
