# Generated by Django 3.0 on 2022-06-14 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0065_studentpending_studentcard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentpending',
            name='identificationNumber',
            field=models.CharField(max_length=11, null=True),
        ),
    ]
