# Generated by Django 3.0 on 2022-07-01 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0072_auto_20220701_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='document1',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='document2',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='document3',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='document4',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
